
//this file is auto generated by `bun run generate-md`

// @ts-expect-error 2614
import FirstPost, { frontmatter as FirstPostMetadata } from "@/blogs/misc/first-post/index.mdx";


import { ContentsCollection } from "@/types";

const contents: ContentsCollection = {
  "first-post": { component: FirstPost, metadata: FirstPostMetadata, category: "misc" },
};

export default contents;